### PR TITLE
Import: Add application/problem+json and application/schema+json to json known mimetypes. #1030

### PR DESCRIPTION
**Pull request by pyrmont**
This imports jneen#1030.

### CODE REVIEW

**Comment by pyrmont** [comment]
@duncangodwin First, could you provide some background for the `application/problem+json` mimetype? I couldn't find anything on it with a cursory search. Something like [the specification](http://json-schema.org/latest/json-schema-core.html) that exists for the `application/schema+json` would be good. 

Second, I'm not sure of the position of the official maintainers but I think this PR should include an update to [the JavaScript spec](https://github.com/jneen/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/spec/lexers/javascript_spec.rb) to check for these mimetypes.

**Comment by duncangodwin** [comment]
@pyrmont Here's a reference to the Problem Details [specification](https://tools.ietf.org/html/rfc7807#section-3) (I've pointed directly at a sample).

I'll have a look at the specs you referenced.

**Comment by pyrmont** [comment]
@duncangodwin Awesome! Not sure why I couldn't find that!

The specific lines to look at are [here](https://github.com/jneen/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/spec/lexers/javascript_spec.rb#L26-L28).

**Comment by pyrmont** [comment]
This is being discussed in rouge-ruby#1030.

**Comment by duncangodwin** [comment]
Thanks @pyrmont!

**Pull request closed without merging**
