### PR TITLE
Import: Add a lexer for ARM assembly files

### PR DESCRIPTION
**Pull request by pyrmont**
This imports jneen#1057.

### CODE REVIEW

**Comment by pyrmont** [comment]
@bavison I'm in the process of trying to create an updated branch of Rouge that merges in some of the backlog of PRs.

One of the PRs I've merged in is [an update to the M68K lexer](https://github.com/jneen/rouge/pull/991) that included a spec for that lexer that's now causing conflicts with your lexer spec. Both lexers could potentially apply if the file extension is `.s` and the system has no way to guess between the two.

The solution to this for other specs is to pass an additional parameter to the `assert_guess` method specifying an example of the `:source` (see, for example, [the Prolog spec](https://github.com/jneen/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/spec/lexers/prolog_spec.rb#L14)). This is then run through the `self.detect?` method by the spec as a way to differentiate between potential matching lexers.

Are you able to add a `self.detect?` method to your PR? I read up a little on ARM assembly but I'm not familiar enough with it to know if there's something unique in the syntax that could be used to identify this particular assembly from others (eg. it seemed like maybe labels don't end in colons in ARM but I'm not sure).

**Comment by bavison** [comment]
Thanks for taking a look. I'm happy enough with regular expressions but a beginner at Ruby, so unless there's something very similar that I can tweak until it works, it'll be difficult for me to code up a `self.detect` method.

I can help with trying to specify it though. You're right, this syntax doesn't use a colon after labels, and labels are always left-aligned. Labels are not quite the only thing that can appear without leading whitespace - an argument to a macro invocation can as well - but since trailing colons are not part of the syntax anywhere else, it's very unlikely any macro arguments would end in a colon either. So matching

^[A-Za-z0-9_]*:

is a pretty good indicator that it's *not* ARM syntax.

Also, if a file doesn't include any non-whitespace characters in column 0, it would be very unlikely to assemble to anything useful. Not sure whether that helps very much though - I'd imagine most other syntaxes at least occasionally contain left-aligned text.

Perhaps the strongest discriminator I can think of is that every ARM assembly file ends with either

^[ \t]+END[; \t\n]

or

^[ \t]+LNK[ \t]

i.e. END can optionally be followed by whitespace and/or a comment, but LNK is followed by whitespace, an argument, and then optional whitespace and/or comment. END and LNK are matched case-sensitively.

Strictly speaking, there could be anything in the lines following the END or LNK directive - the assembler ignores any such lines - but I've never seen an example of anyone putting anything in there, except I can imagine perhaps sometime there are empty lines, or lines containing only whitespace.

Hope this helps.

**Comment by pyrmont** [comment]
@bavison No worries. Thanks for the detailed reply! So are you saying the `END` and `LNK` directives are only used in ARM syntax?

**Comment by bavison** [comment]
To the best of my knowledge, yes. Though it's possible someone else has "borrowed" ARM's syntax. All the toolchains I know of that use this syntax target the ARM CPU exclusively. It's not like GCC syntax, that's cross-platform (but with subtle differences to things like which character introduces comments!)

**Comment by pyrmont** [comment]
After becoming better familiar with how lexers should be written (I've submitted a guide as jneen#1111 so that this can benefit others!), my earlier comment was incorrect. The place to put the disambiguation code is in `lib/rouge/guessers/disambiguation.rb`. I'll get on that as soon as I can :)

**Comment by pyrmont** [comment]
Got this fixed! :)

**Comment by bavison** [comment]
Thanks!

**Pull request merged**
