### PR TITLE
Import: Recognize more Julia types and constants

### PR DESCRIPTION
**Pull request by pyrmont**
This imports jneen#1024.

### CODE REVIEW

**Comment by pyrmont** [comment]
@ararslan It looked like the answer was no but as a sanity check, can you confirm nothing in the fixes to the lexer require changes to [the sample file](https://github.com/jneen/rouge/blob/e957c740ca85b3a96f2cea1e8e1eafbf9cb2abc4/spec/visual/samples/julia)?

**Comment by ararslan** [comment]
I feel like I made the necessary changes to the sample file but it wrecked the tests for some reason so I reverted. Could be misremembering though. There's definitely some stuff that should be adapted in there.

**Comment by pyrmont** [comment]
Hmmm, would it be possible to add some examples using the keywords (eg. `macro`, `mutable`) you added to the lexer? Judging from your earlier messages, I doubt that was the problem but seems like it's worth checking just to be sure.

**Comment by ararslan** [comment]
Sorry I never got around to revisiting this. I'm no longer using GitLab for work, which was why I was interested in improving the rouge Julia definitions in the first place, as GitLab uses that.

**Comment by pyrmont** [comment]
@ararslan No, no—the fault is mine. This PR related to a potential hard fork of Rouge I was considering. Development recommenced on Rouge, though, and _your_ PR (rouge-ruby#1024) was merged. I should have written a better explanation here explaining why it was closed. It's all good! :)

**Pull request closed without merging**
